#pragma once
#ifndef DEVICE_H
#define DEVICE_H

#include "../util/text.h"

#include "gcl.h"

namespace geodesuka {
	namespace core {
		namespace gcl {

			class device {
			public:

				friend class device_context;

				VkPhysicalDeviceProperties Properties;
				VkPhysicalDeviceFeatures Features; 				
				std::vector<VkQueueFamilyProperties> QueueFamilyProperties;

				// Managed by engine, should be generated by engine.
				device(VkInstance *aParentInstance, VkPhysicalDevice aPhysicalDevice);
				~device();

				VkInstance* get_inst();
				VkPhysicalDevice get_handle();

			private:

				// Represents a
				VkInstance* ParentInstance;
				VkPhysicalDevice Handle;

			};

		}
	}
}

#endif // !DEVICE_H
